name: Build and Push a Docker Image

on: [workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: scidb
  VERSION: 19.11

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        OS: [xenial, centos-7]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract and set metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: ${{ env.VERSION }}-${{ matrix.OS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.IMAGE_NAME }}/${{ env.VERSION }}
          file: ${{ env.IMAGE_NAME }}/${{ env.VERSION }}/Dockerfile.${{ matrix.OS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
